# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     volumes:
#       - .:/var/www
#     ports:
#       - "9001:9000"
#       - "8000:8000"
  
#   db:
#     image: mcr.microsoft.com/mssql/server:2019-latest
#     environment:
#       SA_PASSWORD: "Betgox331"
#       ACCEPT_EULA: "Y"
#     ports:
#       - "1433:1433"
#     volumes:
#       - db_data:/var/opt/mssql

# volumes:
#   db_data:


# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     volumes:
#       - .:/var/www
#     ports:
#       - "9001:9000"
#       - "8000:8000"
#     depends_on:
#       - db

#   db:
#     image: mysql:8.0
#     environment:
#       MYSQL_ROOT_PASSWORD: 2603
#       MYSQL_DATABASE: sg
#     ports:
#       - "3306:3306"
#     volumes:
#       - db_data:/var/lib/mysql

# volumes:
#   db_data:


services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    ports:
      - "9001:9000"
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 2603
      MYSQL_DATABASE: sg
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
